all:
  hosts:
  children:
    dokkus:
      hosts:
        hetzner1.whatcanido.org.za:
  vars:
    all_hosts_admins:
      - jdb
    host_extra_admins: [] # Empty default - override this on specific hosts.
