all:
  hosts:
  vars:
    env_name: prod
    all_hosts_admins:
      - jdb
    host_extra_admins: [] # Empty default - override this on specific hosts.
  children:
    dokkus:
      hosts:
        hetzner2.notimon.com:

    notimon:
      hosts:
        hetzner2.notimon.com:
      vars:
        app_domain: notimon.com

    publicpeople:
      hosts:
        hetzner1.whatcanido.org.za:

    devs-exps:
      hosts:
        hetzner2.notimon.com:
      vars:
        app_domain: devs-exps.publicpeople.org.za
