all:
  children:
    publicpeople:
      hosts:
        hetzner1.whatcanido.org.za:
        hetzner2.whatcanido.org.za:

    dokkus:
      hosts:
        hetzner1.whatcanido.org.za:
        hetzner2.whatcanido.org.za:
