all:
  hosts:
  vars:
    env_name: prod
    all_hosts_admins:
      - jdb
    host_extra_admins: [] # Empty default - override this on specific hosts.
  children:
    dokkus:
      hosts:
        hetzner2.notimon.com:

    notimon:
      hosts:
        hetzner1.whatcanido.org.za:
      vars:
        app_domain: notimon.com
        mailbox_domain: mailbox.notimon.com
        default_from_email: noreply@notimon.com
        tag_manager_enabled: "true"
        tag_manager_container_id: "GTM-TXDV43N"
        disable_search_engine_indexing: "false"

    publicpeople:
      hosts:
        hetzner1.whatcanido.org.za:

    devs-exps:
      hosts:
        hetzner2.notimon.com:
      vars:
        app_domain: devs-exps.publicpeople.org.za
