---
- hosts:
    - notimon
  become: true
  roles:
   - dokku_bot.ansible_dokku


  vars:
    app_name: "notimon-{{ env_name }}"
    username: "{{ app_name }}"
    dokku_daemon_install: false # We install this using a dedicated playbook
    dokku_plugins:
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git

  tasks:

    - name: "Dokku app exists"
      dokku_app:
        app: "{{ app_name }}"
      tags:
        - app

    #- name: "Dokku app config is set"
    #  dokku_config:
    #    app: "{{ app_name }}"
    #    config:
    #      AAA: bbb
    #  tags:
    #    - app



    - name: Disable global domain
      dokku_domains:
        app: "{{ app_name }}"
        domains:
          - dokku.me
        state: absent
        global: true
      tags:
        - app

    - name: Remove default domain
      dokku_domains:
        app: "{{ app_name }}"
        domains:
          - "{{ app_name }}.dokku.me"
        state: absent
      tags:
        - app

    - name: ports:set http:80:3000
      dokku_ports:
        app: "{{ app_name }}"
        mappings:
          - http:80:3000

    - name: "Dokku app domains are configured"
      dokku_domains:
        app: "{{ app_name }}"
        domains:
          - "{{ app_domain }}"
      tags:
        - app

    - name: "Your dokku git remote"
      debug:
        msg: "dokku@{{ inventory_hostname }}:{{ app_name }}"
      tags:
        - app
